apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: manpiexcu-python 
  janus-idp.io/tekton: manpiexcu-python
  backstage.io/kubernetes-id: manpiexcu-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: manpiexcu-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml